mutation signupUser(
  $firstName: String!
  $lastName: String!
  $nickName: String!
  $email: String!
  $password: String!
) {
  createUser(
    firstName: $firstName
    lastName: $lastName
    nickName: $nickName
    authProvider: { email: { email: $email, password: $password } }
  ) {
    id
  }
  signinUser(email: { email: $email, password: $password }) {
    token
  }
}
