query currentUser {
	user {
    id
    firstName
    lastName
    nickName
    email
    role
    image {
      id
      name
    }
    document {
      id
      branch
      cellPhone
      dateOfBirth
      department
      employedDate
      idCardNumber
      leaveWithPay
      leaveWithoutPay
      savingsBank
      savingsAccountID
      shift
      timesheets {
        id
        rating
        timeCode
        workday
        remark
      }
    }
  }
}