query allusers {
  allUsers {
    id
    firstName
    lastName
    nickName
    document {
      id
      branch
      department
      timesheets {
        id
        timeCode
        rating
        workday
      }
    }
  }
}